In [2]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# TensorFlow 2 Basics

In this notebook you will:

1. Create and manipulate tensors
2. Build a neural network with Keras
3. Train a regression model
4. Visualize training performance
5. Experiment with architecture choices

Goal: understand the **TensorFlow training pipeline**.

In [3]:
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.20.0


## Exercise 1 — Creating Tensors

Create the following tensors:

1. A scalar tensor with value **5**
2. A vector `[1,2,3,4]`
3. A **3×3 matrix** filled with random numbers

In [8]:
a = tf.constant(5)
b = tf.constant([1, 2, 3, 4])
c = tf.constant(
    [[1.0, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
)
a, b, c

(<tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]], dtype=float32)>)

Inspect the tensor properties (shape, rank, and data type).

In [9]:
c.shape

TensorShape([3, 3])

In [10]:
c.dtype

tf.float32

## Exercise 2 — Tensor Operations

Compute:

1. Element-wise addition
2. Matrix multiplication

In [14]:
A = tf.random.normal((3,3))
B = tf.random.normal((3,2))

# TODO
# A_plus_B = A + B

# TODO
A_times_B = A @ B

A_times_B

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.961692  ,  0.8940174 ],
       [ 0.3442096 , -0.13129804],
       [-2.280388  , -0.44084254]], dtype=float32)>

## Exercise 3 — Generate Regression Data

Create a synthetic regression dataset.

In [15]:
X, y = make_regression(
    n_samples=1000,
    n_features=10,
    noise=15,
    random_state=42
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## Exercise 4 — Build a Neural Network

Build a neural network with:

- 1 hidden layer
- 32 neurons
- ReLU activation

*Hint: use `tf.keras.Sequential` and `tf.keras.layers.Dense`.*

In [ ]:
# TODO

model = tf.keras.Sequential([
    None,
    None
])

model.summary()

## Exercise 5 — Compile the Model

Use:

- optimizer = Adam
- loss = MSE
- metric = MAE

In [ ]:
# TODO

model.compile(
    optimizer=None,
    loss=None,
    metrics=[None]
)

## Exercise 6 — Train the Model

In [ ]:
history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=30,
    batch_size=32
)

## Exercise 7 — Plot Training Curves

*Hint: use the `history` object returned by `model.fit()`.*

In [ ]:
# TODO

plt.plot(None, label="train")
plt.plot(None, label="validation")

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.show()

## Exercise 8 — Evaluate Model

In [ ]:
# TODO

test_metrics = model.evaluate(None, None)

## Exercise 9 — Predictions

## Exercise 10

Modify the model:

1. Add another hidden layer
2. Increase neurons to 64
3. Compare validation loss

Example architecture:

Input → Dense(64) → Dense(64) → Dense(1)